### ISSUE TITLE
Podesiti putanju projektila

### ISSUE THREAD

**Issue by Isa1997** [MATF-RS20/RS025-tanks-an-eve-vay#11]
Treba podesiti putanju projektila da bude kosi hitac. ggwp

**Comment by Isa1997** [comment]
DISCUSS: Should we save angle in degrees or radian? Later on I work with radians (turret rotations feature) and i think it would be waist of time to cast it twice (if i had understood nicely, you have casting too in projectile motion function).

**Comment by AKile9V** [comment]
Dodat je prvi weapon koji je klasicni kosi hitac+eksplozija
