### ISSUE TITLE
Dodati izvestaj za sedmicu 16.12 - 22.12.

### ISSUE THREAD

**Issue by ajzenhamernikola** [MATF-RS20/RS025-tanks-an-eve-vay#3]

**Comment by AKile9V** [comment]
Napisano uz drugu sedmicu jer smo imali problema oko toga u cemu bismo radili, da li u opengl-u ili directx-u, probali smo cak i sa UnrealEngine-om, ali na kraju smo uspeli da pohvatamo stvari sa directx-om pa smo zeleli da se oprobamo u tome.
